local GameConfig = {
	BLOCK_SIZE = 4,
	GRID_COLS = 10,
	GRID_ROWS = 8,
	MAX_BLOCKS_PER_PLAYER = 150,
	MAX_MASS_BUDGET = 500,

	RESOURCES_BASE = 3,
	RESOURCES_PER_TURN_INCREASE = 1,
	MAX_RESOURCES = 8,

	TURN_TIME_SECONDS = 45,
	MATCH_MAX_TURNS = 30,

	CORE_HP = 300,
	SLINGSHOT_LAUNCH_MULTIPLIER = 28,
	MAX_PULL_STUDS = 12,

	TEAM_A_CENTER_X = -40,
	TEAM_B_CENTER_X = 40,
	GROUND_Y = 0.5,

	MAX_SAVED_BLUEPRINTS = 5,
	BLUEPRINT_VERSION = 1,

	DEBRIS_LIFETIME = 2.5,
	MAX_AOE_BLOCKS = 20,
}

return GameConfig
